### ISSUE TITLE
Stopping of containers starts before routes are unregistered

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/rep#18]
We have been observing 502 responses from applications when scaling operations have been performed. Our logs seem to indicate containers are stopped before routes are properly unregistered.

Below is a screenshot of our logs which all contain a reference to a specific container instance GUID. The container was being stopped due to scaling down. The two 'unregister-route' logs are for each of the two availability zones where we have GoRouters. The container in question was in a third AZ in which we don't have GoRouter instances (not sure if that's relevant).

<img width="1182" alt="screen shot 2018-02-15 at 16 10 31" src="https://user-images.githubusercontent.com/8709339/36267165-27875a6c-126b-11e8-893a-436c2b81592a.png">

### Observations

* The stopping of the container process starts 18 milliseconds before the first route unregistration.
* We log the following message 4 milliseconds before the final route unregistration:

  ```
  rep.executing-container-operation.ordinary-lrp-processor.process-reserved-container.run-container.containerstore-run.node-run.action.run-step.process-exit
  ```

  Can you confirm this log is evidence the container is definitely no longer running and will no longer be able to serve traffic?

### Expected behaviour

I would expect the route to be unregistered from all GoRouter instances before any aspect of the container destruction process begins.

### Versions

As pinned by Diego 1.31.0

**Comment by emalm** [comment]
Thanks for the detailed report, @henrytk. You are correct that there can be a race between the propagation of route-unregistration messages and the stopping of containers, as the route-emitter components are effectively observing changes to both desired and actual state and reacting to them to send messages to the rest of the routing control plane. In practice, we believe we have observed a short race not to be an issue for HTTP-handling apps that handle a `TERM` signal "correctly" by ceasing to accept new connections but servicing requests that are still in flight on established connections before closing them. This is because the gorouters will retry other backends when they fail to make a TCP connection to a backend that is registered for a route. If you observed 502 responses from this application, do you happen to know whether it behaves that way in response to a `TERM` signal, or whether it is simply cutting those requests and connections off?

That said, even if the gorouters and cell reps have been coordinating correctly on that behavior, it may be too brittle of a contract to rely on: in fact, the still-experimental work to ensure better integrity and reliability of the HTTP routing tier via using Envoy as a transparent TLS proxy may violate this contract even for these well-behaved apps. We'll take the opportunity both to verify the current behavior and to investigate potential alternatives.

Thanks,
Eric, CF Diego PM

**Comment by mariash** [comment]
Hi @henrytk, we do send Interrupt signal to the container before emitting route unregister event. As @emalm suggested above if app handles interrupt signal correctly and stops servicing new requests there shouldn't be downtime. We do run the tests periodically that test this behavior and have not seen this issue. And since this is an old thread I am going to close the issue.
